using System;
using System.Collections.Generic;
using System.Text;
using Ceiralizer.Generator.Source;

namespace Ceiralizer.Generator;

public class SourceBuilder(int indentSize = 4)
{
    private readonly List<string> _usings = [];
    private string? _namespace;
    private readonly List<ClassBuilder> _classes = [];

    public SourceBuilder Using(string ns)
    {
        _usings.Add(ns); return this;
    }

    public SourceBuilder Namespace(string? ns)
    {
        _namespace = ns;
        return this;
    }

    public SourceBuilder AddClass(string name, Action<ClassBuilder> configure)
    {
        var cb = new ClassBuilder(indentSize).WithName(name);
        configure(cb);
        _classes.Add(cb);
        return this;
    }

    public override string ToString()
    {
        var sb = new StringBuilder("// <auto-generated />\n");

        if (_usings.Count > 0)
        {
            foreach (var u in _usings)
                sb.AppendLine($"using {u};");
            sb.AppendLine();
        }

        if (_namespace is not null && !string.IsNullOrWhiteSpace(_namespace))
            sb.AppendLine($"namespace {_namespace};\n");

        foreach (var cb in _classes)
            sb.Append(cb.Build());

        return sb.ToString();
    }
}